### ISSUE TITLE
ujson build error

### ISSUE THREAD

**Issue by suryasaha** [blobtoolkit/blobtoolkit-docker#5]
Hello!

I'm getting this error when building from the main branch
```
docker build .
Traceback (most recent call last):
  File "/blobtoolkit/blobtools2/lib/add.py", line 71, in <module>
    import bed
  File "/blobtoolkit/blobtools2/lib/bed.py", line 16, in <module>
    from tolkein import tofile
  File "/home/blobtoolkit/miniconda3/envs/btk_env/lib/python3.8/site-packages/tolkein/__init__.py", line 4, in <module>
    from .lib import tofetch
  File "/home/blobtoolkit/miniconda3/envs/btk_env/lib/python3.8/site-packages/tolkein/lib/tofetch.py", line 17, in <module>
    from .tofile import write_file
  File "/home/blobtoolkit/miniconda3/envs/btk_env/lib/python3.8/site-packages/tolkein/lib/tofile.py", line 17, in <module>
    import ujson
ModuleNotFoundError: No module named 'ujson'
```

My dev env is 
`Linux ABC 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`

**Comment by rjchallis** [comment]
Thanks for flagging this error. There was a python mismatch between the container and the modules as the container version bumped to 3.9 in newer builds without me realising. I've added the btk_env python to the PATH in the docker file so new builds should work.
